Add Course Management UI
smacademic/project-GEEKS pull request #24
Opened 2019-03-03 18:25 UTC by kozlowskik

The following changes were made to the `index.html` page:
- Added comments to the end of all major sections of the body.
- Added the div for Course Management
- Added the drop-down menus to select the `year` and `season` so that they can be determined
    - Renamed the `ID` attributes to reflect that these drop downs should be seen by the *Registrar*, new titles now are `reg_yearSelect` and `reg_seasonSelect`
- Added text input fields to add a new course
    - Text fields include `Course Number`, `Course Title`, `Credits`
- Added a button at the end of the input field row to submit the information to the backend before going to the DB.

2019-03-03 21:54 UTC, fitz-cris requested changes
At the moment, the course_mgmt tab contains season and year dropdown menus. Courses, as I understand them, are independent of seasons and years. Sections, on the other hand, do require season and year information, though we have not reached section implementation yet.

2019-03-03 22:04 UTC, fitz-cris commented
The current implementation does require a year and season in order to return a list of courses, but returns only a list of courses that a specific instructor has taught at a given time. As I understand our current objective, we are implementing the addition of university level courses, separate from any given time period. If there are reasons to add a season and year to a course, then our conceptual and logical schema should reflect that.

2019-03-04 03:20 UTC, fitz-cris approved these changes

2019-03-04 03:20 UTC, griffine approved these changes

2019-03-04 03:26 UTC, DasilvaB approved these changes

2019-03-04 03:27 UTC, merged