Update addCourseMgmt.sql
smacademic/project-GEEKS pull request #52
Opened 2019-03-19 17:31 UTC by griffine

Added 'modifyCourse' function and 'courseExists' function to addCourseMgmt.sql.

Implemented the 'courseExists' function into the 'insertCourse' and 'removeCourse' functions in place of the previous 'IF EXISTS (...)' tests

Changed around some of the formatting of lines to be more readable and clean.

2019-03-19 17:47 UTC, kozlowskik requested changes

2019-03-19 17:47 UTC, kozlowskik commented on src/db/addCourseMgmt.sql
> +         SELECT * FROM Course WHERE Course.Number = cNumber
This will probably need to be changed to say `Gradebook.Course`

2019-03-19 17:47 UTC, kozlowskik commented on src/db/addCourseMgmt.sql
> +      SELECT * FROM Course WHERE Course.Number = cNumber
This too will probably need to say `Gradebook.Course`

2019-03-19 19:50 UTC, kozlowskik approved these changes

2019-03-19 23:00 UTC, DasilvaB approved these changes
looks good

2019-03-20 14:28 UTC, fitz-cris approved these changes
good catch Ken, otherwise looks good to go

2019-03-22 01:13 UTC, merged